services:
  postgres:
    image: postgres:15
    container_name: postgres_medical
    environment:
      POSTGRES_DB: medical_appointment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  medicalappointment.api:
    build:
      context: ./MedicalAppointment.Api
      dockerfile: Dockerfile
    container_name: medical_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=medical_appointment;Username=postgres;Password=postgres123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - medical_network
  
  frontend:
    build:
      context: ./MedicalAppointment.Api/front-end
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_BASE: http://medicalappointment.api:8080
    container_name: medical_frontend
    ports:
      - "3000:3000"
    depends_on:
      medicalappointment.api:
        condition: service_started
    networks:
      - medical_network

volumes:
  postgres_data:

networks:
  medical_network:
    driver: bridge